### ISSUE TITLE
Is it possible to connect SQID to your own SPARQL endpoint?

### ISSUE THREAD

**Issue by szeke** [Wikidata/SQID#141]
We have our own sparql endpoint running wikidata, and would like to connect SQID to it. Is this possible?

Also, we are adding more items and statements to our sparql endpoint. Will SQID recognize them?

**Comment by mmarx** [comment]
It's certainly possible, although currently not trivial to accomplish: you'll have to change all references to API/SPARQL endpoints in SQID to point to your wikibase installation. Unfortunately, those are scattered all over the source code (though they should be easy enough to find). I plan on moving all endpoint URIs to a central location in a future release, but there is no timeline for when that might happen.

Since almost all data is fetched from the API and the SPARQL endpoint, once you point them at your data, SQID will pick up any changes you make there, and you can also use wikidata-toolkit to generate statistics data files for your instance.

**Comment by szeke** [comment]
Maximilian,

Thanks for the response. I will look for a student who can work on this during the summer. If we do it, we’ll do a pull request.

p

**Comment by mmarx** [comment]
Done in 153b24d3f435d923e24b4ad4564fa69098d4f8ea.

**Comment by szeke** [comment]
Thanks for solving this issue
